[Desktop Entry]
Type=X-GNOME-Metatheme
Name=gruvbox-medium-dark-green
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=gruvbox-medium-dark-green
GtkTheme=gruvbox-medium-dark-green
IconTheme=gruvbox-medium-dark-green
MetacityTheme=gruvbox-medium-dark-green
